preview_adhan:
  name: "[%key:component::nida::services::preview_adhan::name%]"
  description: "[%key:component::nida::services::preview_adhan::description%]"
  fields:
    sound:
      name: "[%key:component::nida::services::preview_adhan::fields::sound::name%]"
      description: "[%key:component::nida::services::preview_adhan::fields::sound::description%]"
      required: true
      selector:
        select:
          options:
          - label: 01 Adhan Fajr
            value: 01-adhan-fajr.mp3
          - label: 02 Adhan Fajr
            value: 02-adhan-fajr.mp3
          - label: 03 Adhan Fajr
            value: 03-adhan-fajr.mp3
    speaker:
      name: "[%key:component::nida::services::preview_adhan::fields::speaker::name%]"
      description: "[%key:component::nida::services::preview_adhan::fields::speaker::description%]"
      required: true
      selector:
        entity:
          domain: media_player
    volume:
      name: "[%key:component::nida::services::common::fields::volume::name%]"
      description: "[%key:component::nida::services::common::fields::volume::description%]"
      required: false
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

test_prayer:
  name: "[%key:component::nida::services::test_prayer::name%]"
  description: "[%key:component::nida::services::test_prayer::description%]"
  fields:
    prayer:
      name: "[%key:component::nida::services::common::fields::prayer::name%]"
      description: "[%key:component::nida::services::common::fields::prayer::description%]"
      required: true
      default: dhuhr
      selector:
        select:
          options:
          - label: Fajr
            value: fajr
          - label: Dhuhr
            value: dhuhr
          - label: Asr
            value: asr
          - label: Maghrib
            value: maghrib
          - label: Isha
            value: isha
          - label: "Jumat (vrijdag)"
            value: jumat

test_tarhim:
  name: "[%key:component::nida::services::test_tarhim::name%]"
  description: "[%key:component::nida::services::test_tarhim::description%]"
  fields:
    sound:
      name: "[%key:component::nida::services::test_tarhim::fields::sound::name%]"
      description: "[%key:component::nida::services::test_tarhim::fields::sound::description%]"
      required: false
      selector:
        select:
          options:
          - label: 01 Tarhim
            value: 01-tarhim.mp3
          - label: 02 Tarhim
            value: 02-tarhim.mp3
    speaker:
      name: "[%key:component::nida::services::common::fields::speaker::name%]"
      description: "[%key:component::nida::services::common::fields::speaker::description%]"
      required: false
      selector:
        entity:
          domain: media_player
    volume:
      name: "[%key:component::nida::services::common::fields::volume::name%]"
      description: "[%key:component::nida::services::common::fields::volume::description%]"
      required: false
      default: 0.4
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

test_reminder:
  name: "[%key:component::nida::services::test_reminder::name%]"
  description: "[%key:component::nida::services::test_reminder::description%]"
  fields:
    reminder:
      name: "[%key:component::nida::services::test_reminder::fields::reminder::name%]"
      description: "[%key:component::nida::services::test_reminder::fields::reminder::description%]"
      required: false
      default: 1
      selector:
        select:
          options:
          - label: Reminder 1
            value: 1
          - label: Reminder 2
            value: 2
    prayer:
      name: "[%key:component::nida::services::common::fields::prayer::name%]"
      description: "[%key:component::nida::services::common::fields::prayer::description%]"
      required: false
      default: Dhuhr
      selector:
        select:
          options:
          - label: Fajr
            value: Fajr
          - label: Dhuhr
            value: Dhuhr
          - label: Asr
            value: Asr
          - label: Maghrib
            value: Maghrib
          - label: Isha
            value: Isha

test_notification:
  name: "[%key:component::nida::services::test_notification::name%]"
  description: "[%key:component::nida::services::test_notification::description%]"
  fields: {}
test_suhoor:
  name: "[%key:component::nida::services::test_suhoor::name%]"
  description: "[%key:component::nida::services::test_suhoor::description%]"
  fields: {}
